# Server Config
server.port=8080

# File uploads NUEVO PROYECTO
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB

# PostgreSQL Data Source Config
spring.datasource.url=jdbc:postgresql://localhost:5432/demo1
spring.datasource.username=postgres
spring.datasource.password=Joseelmer31
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging Config (Show only errors and important info)
logging.level.root=INFO
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR
